# Generated by Django 5.0.8 on 2024-08-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_site', models.URLField()),
                ('nom_fichier', models.CharField(max_length=255)),
                ('avancement', models.IntegerField(default=0)),
                ('Statut', models.CharField(choices=[('Succès', 'Succès'), ('En Cours', 'En cours'), ('Échec', 'Échec')], default='En cours', max_length=12)),
                ('date_debut', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('specialite', models.CharField(blank=True, max_length=300)),
                ('Categories', models.TextField(blank=True)),
            ],
        ),
    ]
