# Generated by Django 5.0.8 on 2024-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='option',
            field=models.CharField(choices=[('toutes', 'toutes'), ('actuelle', 'actuelle'), ('personnaliser', 'personnalisé')], default='actuelle', max_length=20),
        ),
    ]
