# Generated by Django 5.0.8 on 2024-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0002_projects_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='pages',
            field=models.CharField(default='', max_length=50),
        ),
    ]
