# Generated by Django 5.0.8 on 2024-08-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0003_projects_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='pages',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
