# Generated by Django 5.0.8 on 2024-08-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0004_alter_projects_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='option',
            field=models.CharField(choices=[('Toutes', 'Toutes'), ('Actuelle', 'Actuelle'), ('Personnaliser', 'Personnaliser')], default='actuelle', max_length=20),
        ),
    ]
