# Generated by Django 5.0.8 on 2024-08-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0005_alter_projects_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='avancement',
            new_name='progress',
        ),
        migrations.AddField(
            model_name='projects',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
